### ISSUE TITLE
ECLKC and iPD error messages and inability to click on buttons

### ISSUE THREAD

**Issue by bkingztt** [OHS-Hosting-Infrastructure/infrastructure#189] opened 2021-08-17 13:03 UTC
## Reported By
Brittany King (bking@zerotothree.org)

## Application Context
ECLKC and iPD

## Environment Context
Production

## Describe the issue
When I log in to the ECLKC, I get a message that says either the page isn't working (I've been redirected too many times) or the page isn't redirecting properly. After a few tries, I'm able to get logged in and can access the iPD. However, once in the iPD nothing happens when I click on some of the buttons.

## Impact
*All end users.

## How To Reproduce
Log in to the ECLKC or press the name button when you're in a student account on the iPD (located in the upper right hand corner)

### Reproducibility
Always

<img width="1358" alt="Screen Shot 2021-08-17 at 8 33 25 AM" src="https://user-images.githubusercontent.com/88720340/129730281-d9fa254b-b63f-4ac2-852a-ebaf679a6e9a.png">
![3f4fda0a-0af8-44ba-b365-03267ae09315](https://user-images.githubusercontent.com/88720340/129730334-99bf2164-972e-40d5-990a-5fa2e71c0dd1.jpg)

**Comment by ssatagopan** [comment] 2021-08-17 13:21
@bkingztt I was able to reproduce, but then when I go back to ECLKC home page, it shows me as logged in. Does that work for you?

**Comment by bkingztt** [comment] 2021-08-17 13:25
Yes. I can get logged in after a few tries. However, once I'm logged in, I am not able to fully use the iPD.


Brittany R. King (She/Her)

Senior LMS Administrator
National Center on Early Childhood Development, Teaching, and Learning
Telephone: (202) 857-2666 | Email: ***@***.******@***.***>

[cid:28017805-8df9-4f5c-821f-9ffa75b11532]
________________________________

**Comment by ssatagopan** [comment] 2021-08-17 13:31
Ok thank you, we were having some issues with the site overnight due to some unexpected traffic. We will take a look at this combined with that.

**Comment by bkingztt** [comment] 2021-08-17 13:32
Thank you!


Brittany R. King (She/Her)

Senior LMS Administrator
National Center on Early Childhood Development, Teaching, and Learning
Telephone: (202) 857-2666 | Email: ***@***.******@***.***>

[cid:998f092f-c9a0-418a-a430-7a0c234a5fd5]
________________________________

**Comment by bkingztt** [comment] 2021-08-17 18:01
Hi! Any update on the ECLKC and iPD?


Brittany R. King (She/Her)

Senior LMS Administrator
National Center on Early Childhood Development, Teaching, and Learning
Telephone: (202) 857-2666 | Email: ***@***.******@***.***>

[cid:c5c2a64f-fffc-4b18-a473-190a9467d5b3]
________________________________

**Comment by ssatagopan** [comment] 2021-08-17 19:52
@bkingztt We have resolved the login issues but we think the user profile issue may be something on the iPD side. Has your team already investigated that?

**Comment by bkingztt** [comment] 2021-08-17 20:01
I've asked them to take a look. However, I'm still running into this issue when I try to log in to the iPD.

[cid:1cfa19bb-9b26-49d7-a9f1-d2a0381b0f65]


Brittany R. King (She/Her)

Senior LMS Administrator
National Center on Early Childhood Development, Teaching, and Learning
Telephone: (202) 857-2666 | Email: ***@***.******@***.***>

[cid:8fee78a0-83f3-4ecf-8c1f-2d2602fad8a9]
________________________________

**Comment by ssatagopan** [comment] 2021-08-17 20:06
> I've asked them to take a look. However, I'm still running into this issue when I try to log in to the iPD. 

Do you mean the page about too many redirects? Not sure what you meant by "this issue"

**Comment by bkingztt** [comment] 2021-08-17 20:10
Yes. The issues I'm talking about it the too many redirects message and just the fact that, if/when you are able to log in, pages won't load or load slowly.


Brittany R. King (She/Her)

Senior LMS Administrator
National Center on Early Childhood Development, Teaching, and Learning
Telephone: (202) 857-2666 | Email: ***@***.******@***.***>

[cid:733e1a66-da56-4825-9208-e990c9cdb1d4]
________________________________

**Comment by ssatagopan** [comment] 2021-08-17 20:35
I do see the too many redirects page come up, but it then goes away without any action from me and takes me into the app.

**Comment by bkingztt** [comment] 2021-08-17 21:46
Ok. I've asked Paradiso to take a look. I'm cc'ing them on this email, so everyone can stay in the loop.


Brittany R. King (She/Her)

Senior LMS Administrator
National Center on Early Childhood Development, Teaching, and Learning
Telephone: (202) 857-2666 | Email: ***@***.******@***.***>

[cid:31cc64c6-deda-493b-a7c4-571207a99ef2]
________________________________

**Comment by bkingztt** [comment] 2021-08-18 12:31
Hi Team.
Appears to be some javascript issue. Maybe caused for insertions during the pentesting.
Seems that were some content inserted blocking javascript. Maybe them removed. I'll check if i can find something in logs but im not sure of finding something helpful.

Regards, Ever G.
________________________________

**Comment by ssatagopan** [comment] 2021-08-18 13:14
If we are able to provide DB dumps to you, would that help with your investigation?

**Comment by bkingztt** [comment] 2021-08-18 14:10
Yes, please.


Brittany R. King (She/Her)

Senior LMS Administrator
National Center on Early Childhood Development, Teaching, and Learning
Telephone: (202) 857-2666 | Email: ***@***.******@***.***>

[cid:1bd9d99a-f91a-4063-9438-6cb516aa4028]
________________________________

**Comment by jerels** [comment] 2021-08-18 19:07
@bkingztt tried getting a db dump going, but seems to have messed with the functionality of ipd site. i could try again during the maintenance window tomorrow, if it's still needed

**Comment by rpdelaney** [comment] 2022-01-26 22:31
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.

**Closed by rpdelaney** 2022-01-26 22:31 UTC
Labels: type:bug, state:to-triage
